import psycopg2
from psycopg2 import sql
import datetime
import uuid
from random import randint


# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host= "127.0.0.1",
    database= "postgres",
    user="postgres",
    password="tcc_univesp!"
)

# Create a cursor object to execute SQL queries
cur = conn.cursor()

# Define the INSERT queries with placeholders for the data

insertItem = sql.SQL("INSERT INTO public.\"Item\"( \
	id, name, type, \"createdAt\", deleted, updated) \
	VALUES (%s, %s, %s, %s, %s, %s);")
		 


createdAt = datetime.datetime.now() 


name = []	


name.append("-")
name.append("8 Bp 398")
name.append("8 Bp 399")
name.append("8 Bp 400")
name.append("9 Bp 210")
name.append("9 Dp 152")
name.append("Abraçadeira")
name.append("Abraçadeira 32/44")
name.append("Abraçadeira 7 mm")
name.append("Abraçadeira Aditivo")
name.append("Abraçadeira Coifa")
name.append("Abraçadeira Coifa Câmbio")
name.append("Abraçadeira Distribuidor")
name.append("Abraçadeira Escapamento")
name.append("Abraçadeira Grande")
name.append("Abraçadeira Grande Radiador")
name.append("Abraçadeira Inferior Mangueira Reservatório")
name.append("Abraçadeira Mangueira")
name.append("Abraçadeira Mangueira Ar Quente")
name.append("Abraçadeira Média Grande")
name.append("Abraçadeira Media Reservatório")
name.append("Abraçadeira Pequena")
name.append("Abraçadeira S/Fim 14x22 Fita")
name.append("Abraçadeira S/Fim 32x44 Fita")
name.append("Abrir Rosca")
name.append("Aceleração")
name.append("Acertar O Ponto")
name.append("Acerto Ponto")
name.append("Acionamento Ventoinha")
name.append("Acoplamento")
name.append("Acoplamento Alavanca")
name.append("Acoplamento Câmbio")
name.append("Acoplamento Coluna Direção")
name.append("Acoplamento Completo")
name.append("Acoplamento Trambulador")
name.append("Adaptador")
name.append("Adaptador Cavalete Água")
name.append("Adaptador Coletor")
name.append("Aditivo")
name.append("Aditivo Limpeza Bico")
name.append("Aditivo Radiador")
name.append("Aditivo Radiador Azul")
name.append("Aditivo Radiador Orgânico")
name.append("Aditivo Radiador Rosa")
name.append("Aditivo Radiador UT-15")
name.append("Aditivo Radiador Verde")
name.append("Aditivo Radiador Vermelho")
name.append("Agregado")
name.append("Água Desmineralizada")
name.append("Agulha")
name.append("Agulha Boia")
name.append("Agulha Carburador")
name.append("Agulha Medida 200")
name.append("Ajustados Os Tensor Correia")
name.append("Ajuste")
name.append("Ajuste Alavanca")
name.append("Ajuste Alavanca Câmbio")
name.append("Alavanca")
name.append("Alavanca Câmbio")
name.append("Alavanca Engate")
name.append("Alavanca Freio Mão")
name.append("Alavanca Marcha")
name.append("Alavanca Porta Traseira")
name.append("Alavanca Retrovisor")
name.append("Alavanca Seletora")
name.append("Alavanca Trambulador")
name.append("Alça Escapamento")
name.append("Álcool")
name.append("Alinhamento")
name.append("Alinhamento Balanceamento")
name.append("Alinhamento Balanceamento Cambagem")
name.append("Alinhamento Cambagem")
name.append("Alinhamento Dianteiro")
name.append("Alinhamento Mancal")
name.append("Alinhamento Técnico")
name.append("Alternador")
name.append("Amortecedor")
name.append("Amortecedor Dianteiro")
name.append("Amortecedor Dianteiro Lado Esquerdo")
name.append("Amortecedor Dianteiro Recom")
name.append("Amortecedor Dianteiro Remano")
name.append("Amortecedor Dianteiro Usado")
name.append("Amortecedor Direção")
name.append("Amortecedor Porta Mala")
name.append("Amortecedor Suspensão")
name.append("Amortecedor Suspensão Dianteiro")
name.append("Amortecedor Tampa Traseira")
name.append("Amortecedor Traseiro")
name.append("Amortecedor Traseiro Remano")
name.append("Amortecedores")
name.append("Amortecedores 2 Traseiro")
name.append("Amortecedores Dianteiro")
name.append("Amortecedores Dianteiros")
name.append("Amortecedores Traseiro")
name.append("Analise Geral Gás")
name.append("Anéis Bico")
name.append("Anéis Encosto Stander")
name.append("Anéis Std")
name.append("Anel")
name.append("Anel 050")
name.append("Anel Anicha")
name.append("Anel Anti Chama")
name.append("Anel Bico")
name.append("Anel Bobina")
name.append("Anel Bocal")
name.append("Anel Bocal Tanque")
name.append("Anel Bomba")
name.append("Anel Bomba Água")
name.append("Anel Bujão")
name.append("Anel Bujão Óleo")
name.append("Anel Cárter")
name.append("Anel Coletor")
name.append("Anel Distribuidor")
name.append("Anel Diversos")
name.append("Anel Encosto")
name.append("Anel Encosto 050")
name.append("Anel Encosto Bronzina")
name.append("Anel Encosto Bronzina Mancal Std")
name.append("Anel Encosto Mancal")
name.append("Anel Escapamento")
name.append("Anel Flange Bomba Comb.")
name.append("Anel Injetor Gás")
name.append("Anel Lateral")
name.append("Anel Motor")
name.append("Anel O-ring")
name.append("Anel O-ring Bobina")
name.append("Anel O-ring Camisa")
name.append("Anel O-ring Distribuidor")
name.append("Anel O-ring Tampa Bobina")
name.append("Anel O-ring Vedação")
name.append("Anel O-ring Volante")
name.append("Anel Pescador")
name.append("Anel Pistão")
name.append("Anel Pistão 040")
name.append("Anel Reservatório")
name.append("Anel Reservatório Gás")
name.append("Anel Respiro")
name.append("Anel Sincronizado")
name.append("Anel Sincronizado 1ª 2ª")
name.append("Anel Sincronizado 2ª 3ª")
name.append("Anel Sincronizado 1ª 2ª 3ª 4ª")
name.append("Anel Sincronizado 1ª 4ª")
name.append("Anel Sincronizado 3ª 4ª")
name.append("Anel Sincronizado 5ª")
name.append("Anel Sincronizado Ré")
name.append("Anel Std")
name.append("Anel Tampa")
name.append("Anel Tampa Bobina")
name.append("Anel Tampa Válvula Respiro Motor")
name.append("Anel Tubo Óleo")
name.append("Anel Válvula")
name.append("Anel Válvula Termostática")
name.append("Anel Vedação")
name.append("Anel Vedação Anti Chama")
name.append("Anel Vedação Bobina")
name.append("Anel Vedação Bomba Combustível")
name.append("Anel Vedação Carcaça")
name.append("Anel Vedação D/Anti Chama")
name.append("Anel Vedação Distribuidor")
name.append("Anel Vedação Reservatório")
name.append("Anel Vedação Tampa")
name.append("Anel Vedação Vareta Óleo")
name.append("Anel Volante")
name.append("Anel Volante Motor")
name.append("Anelzinho Vira")
name.append("Anti Chama")
name.append("Anti Chama Com Mangueira")
name.append("Antena")
name.append("Anti Chama Com Rabicho Longo")
name.append("Anti Chama Motor")
name.append("Anti Chama Ponta Fixa")
name.append("Aparelho Injeção")
name.append("Aperto fuso Freio Dianteiro")
name.append("Aperto fuso Pedal")
name.append("Aperto fuso Roda Traseira")
name.append("Aperto Na Abraçadeira")
name.append("Aperto Na Suspensão")
name.append("Apertou Junta Carte")
name.append("Retífica Cabeçote")
name.append("Ar Sistema Freio")
name.append("Arruela")
name.append("Arruela Bujão Cárter")
name.append("Arruela Cabeçote")
name.append("Arruela Eixo Traseiro")
name.append("Arruela Encosto Std")
name.append("Arruela Encosto Virabrequim")
name.append("Arruela Pinhão Distribuidor")
name.append("Arruela Regulagem")
name.append("Articulação Axial")
name.append("Articulação Caixa")
name.append("Articulação Caixa Direção Hidráulica")
name.append("Articulação Caixa Direção Com Coifa")
name.append("Árvore Manivela")
name.append("Árvore Primaria")
name.append("Assoalho Lado Direito")
name.append("Assoalho Lado Esquerdo")
name.append("Atuador")
name.append("Atuador Auxiliar Embreagem")
name.append("Atuador Câmbio")
name.append("Atuador Embreagem")
name.append("Atuador Hidráulico")
name.append("Atuador Lado Esquerdo")
name.append("Atuador Marcha Lado Esquerdo")
name.append("Atuador Marcha")
name.append("Atuador Pedal Embreagem")
name.append("Atuador Posição Borboleta")
name.append("Serviço Elétrica em Terceirizada")
name.append("B. Biela")
name.append("B. Comando")
name.append("B. Mancal")
name.append("Bacalhau Traseiro")
name.append("Bandeja")
name.append("Baixinho")
name.append("Baixinho Que Atendeu")
name.append("Balancim")
name.append("Balanceamento")
name.append("Balancim Motor")
name.append("Bamba Combustível")
name.append("Bamba D'água")
name.append("Bandeja Inferior Lado Direito")
name.append("Bandeja Inferior Lado Esquerdo")
name.append("Bandeja Inferior Lado Direito Com Bucha")
name.append("Bandeja Superior Lado Direito")
name.append("Bandeja Superior Lado Esquerdo")
name.append("Bandeja Superior Lado Direito Com Bucha")
name.append("Banho Químico")
name.append("Banho Químico Com Selo")
name.append("Baquelite")
name.append("Baquelite Bomba Combustível")
name.append("Barra Axial Caixa Direção Lado Esquerdo")
name.append("Barra Axial Caixa Direção Lado Direito")
name.append("Barra Direção Central")
name.append("Barra Direção Lado Esquerdo")
name.append("Barra Direção Lado Direito")
name.append("Barra Estabilizadora")
name.append("Barra Fixação Pivô")
name.append("Barra Tensora")
name.append("Bateira 45 Ah")
name.append("Batente")
name.append("Batente Amortecedor Dianteiro Lado Direito")
name.append("Batente Amortecedor Dianteiro Lado Esquerdo")
name.append("Batente Amortecedor Traseiro Lado Direito")
name.append("Batente Amortecedor Traseiro Lado Esquerdo")
name.append("Batente Bandeja")
name.append("Batente Coluna Amortecedor")
name.append("Batente Diabinho")
name.append("Batente Dianteiro Bandeja")
name.append("Batente Feixe Mola")
name.append("Batente Lateral")
name.append("Batente Prato")
name.append("Bateria 50 Ah")
name.append("Bateria 60 Ah")
name.append("Bico Injetor")
name.append("Bico Injetor Álcool")
name.append("Bronzina 025")
name.append("Biela")
name.append("Mancal")
name.append("Bieleta Estabilizadora Dianteiro Direito")
name.append("Bieleta Estabilizadora Dianteiro Esquerda")
name.append("Bieleta Estabilizadora Traseira Direito")
name.append("Bieleta Estabilizadora Traseira Esquerda")
name.append("Bloco")
name.append("Bloco Alinhamento Mancal")
name.append("Bloco Banho Químico")
name.append("Bloco Banho Químico Com Selos")
name.append("Bloco Encamisar")
name.append("Bloco Motor")
name.append("Bloco Retifica")
name.append("Bobina")
name.append("Bobina 2 Cilindro")
name.append("Bobina Com Cabos Vela Ignição")
name.append("Bobina Ignição")
name.append("Borboleta Cabo Embreagem")
name.append("Bocal Enchimento")
name.append("Bocal Tanque")
name.append("Boia Carburador")
name.append("Boia Combustível")
name.append("Boia Reservatório Partida Frio")
name.append("Bolacha Homocinética Interna")
name.append("Bomba Água")
name.append("Bomba Água Com Polia Direção")
name.append("Bomba Combustível")
name.append("Bomba Combustível Completa")
name.append("Bomba D'água")
name.append("Bomba Direção Hidráulica")
name.append("Bomba Óleo")
name.append("Bomba Refil")
name.append("Bomba Vácuo")
name.append("Borboleta")
name.append("Borracha")
name.append("Borracha Junção Coletor")
name.append("Borracha Anti Chama")
name.append("Borracha Bocal Tanque")
name.append("Borracha Coletor Admissão")
name.append("Borracha Coxim Motor")
name.append("Borracha Escapamento")
name.append("Borracha Fixação Caixa")
name.append("Borracha Hidrovácuo")
name.append("Borracha Pedal Acelerador")
name.append("Borracha Portas")
name.append("Borracha Radiador Óleo")
name.append("Borracha Reservatório Gasolina")
name.append("Borracha Respiro Motor")
name.append("Borracha Respiro Tampa Válvula")
name.append("Borracha Suspensão")
name.append("Borracha Tampa Bomba Combustível")
name.append("Borracha Vedação Bomba Combustível")
name.append("Braçadeira")
name.append("Braçadeira 7 mm")
name.append("Braçadeira Coifa Câmbio")
name.append("Braçadeira Mangueira Ar Quente")
name.append("Braçadeira Mangueira Filtro Ar")
name.append("Braçadeira Mangueira Gasolina")
name.append("Braçadeira Pequena")
name.append("Braçadeira Radiador")
name.append("Braçadeira Radiador Grande")
name.append("Braçadeira Coifa Lado Câmbio")
name.append("Braçadeira Grande")
name.append("Braçadeira Médias")
name.append("Braçadeira Mangueira Radiador")
name.append("Braco Articulação Caixa")
name.append("Braço Auxiliar")
name.append("Braco Auxiliar Caixa Direção")
name.append("Braço Auxiliar Lado Direito Não Tem")
name.append("Braço Axial")
name.append("Braço Axial Caixa")
name.append("Braco Axial Caixa Direção")
name.append("Braço Axial Caixa Direção")
name.append("Braço Axial Caixa Estabilizadora")
name.append("Braço Caixa Direção")
name.append("Braco Estabilizador Traseiro Com Bucha")
name.append("Braço Limpador")
name.append("Braco Mutante")
name.append("Braco Oscilante Caixa Direção")
name.append("Braço Oscilante Caixa Direção")
name.append("Braço Oscilante Com Pivô")
name.append("Braço Tensor")
name.append("Brisa")
name.append("Bronzina Biela")
name.append("Bronzina Biela 020")
name.append("Bronzina Biela 025")
name.append("Bronzina Biela 030")
name.append("Bronzina Biela 050")
name.append("Bronzina Biela 075")
name.append("Bronzina Biela Std")
name.append("Bronzina Comando")
name.append("Bronzina Encosto")
name.append("Bronzina Encosto Std")
name.append("Bronzina Lateral")
name.append("Bronzina Lateral 012")
name.append("Bronzina Lateral Std")
name.append("Bronzina Mancal")
name.append("Bronzina Mancal 025")
name.append("Bronzina Mancal 030")
name.append("Bronzina Mancal 050")
name.append("Bronzina Mancal 075")
name.append("Bronzina Mancal Std")
name.append("Bucha")
name.append("Bucha Aço Braço Oscilante")
name.append("Bucha Agregado Traseiro")
name.append("Bucha Alavanca")
name.append("Bucha Amortecedor Traseiro")
name.append("Bucha Amortecedor Dianteiro")
name.append("Bucha Arvore Direção")
name.append("Bucha Bandeja")
name.append("Bucha Bandeja Dianteira")
name.append("Bucha Bandeja Inferior")
name.append("Bucha Bandeja Lado Direito")
name.append("Bucha Bandeja Lado Esquerdo")
name.append("Bucha Bandeja Superior")
name.append("Bucha Bandeja Traseira Inferior")
name.append("Bucha Bandeja Traseira Superior")
name.append("Bucha Barra Direção")
name.append("Bucha Barra Estabilizadora")
name.append("Bucha Barra Estabilizadora Dianteiro")
name.append("Bucha Barra Estabilizadora Ponta")
name.append("Bucha Barra Estabilizadora Traseira")
name.append("Bucha Biela")
name.append("Bucha Borracha Haste Volante")
name.append("Bucha Braço")
name.append("Bucha Braco Caixa Direção")
name.append("Bucha Braço Oscilante")
name.append("Bucha Braco Pivô")
name.append("Bucha Braço Tensor")
name.append("Bucha Cabo")
name.append("Bucha Caixa Direção")
name.append("Bucha Coletor Escape")
name.append("Bucha Coluna Direção")
name.append("Bucha Eixo Traseiro")
name.append("Bucha Eletrobomba")
name.append("Bucha Eletroválvula")
name.append("Bucha Escapamento")
name.append("Bucha Estirante")
name.append("Bucha Ferro Braco Oscilante")
name.append("Bucha Fixação Caixa")
name.append("Bucha Mancal")
name.append("Bucha Morceguinho")
name.append("Bucha Partida Frio")
name.append("Bucha Pedal Freio")
name.append("Bucha Pedal Acelerador")
name.append("Bucha Pedal Embreagem")
name.append("Bucha Pneuzinho Braco Tensor Suspensão")
name.append("Bucha Pneuzinho Tirante")
name.append("Bucha Varão Ponta")
name.append("Bucha Quadro Dianteiro")
name.append("Bucha Quadro Motor")
name.append("Bucha Quadro Suspensão")
name.append("Bucha Quadro Traseiro")
name.append("Bucha Radiador")
name.append("Bucha Reservatório D'água")
name.append("Bucha Rolamento")
name.append("Bucha Suspensão")
name.append("Bucha Suspensão Traseira")
name.append("Bucha Suspensão Traseira Ferro")
name.append("Bucha Tensor")
name.append("Bucha Tensor Dianteiro")
name.append("Bucha Terminal Direção")
name.append("Bucha Tirante")
name.append("Bucha Trambulador")
name.append("Bucha Bandeja Traseira")
name.append("Bucha Vampiro")
name.append("Bucha Varão")
name.append("Bucha Varão Alavanca")
name.append("Bucha Varão Câmbio")
name.append("Bucha Vareta Óleo")
name.append("Bucha Vedação")
name.append("Bujão")
name.append("Bujão Carte")
name.append("Bujão Carte Com Arruela")
name.append("Bujão Cárter")
name.append("Bujão Com Rosca")
name.append("Bujão Gaiola")
name.append("Bujão Óleo")
name.append("Buzina")
name.append("Buzina Caracol")
name.append("Cabeçote")
name.append("Cabeçote Completo")
name.append("Cabo")
name.append("Cabo Acelerador")
name.append("Cabo Afogador")
name.append("Cabo Alavanca Marcha")
name.append("Cabo Conexão")
name.append("Cabo Embreagem")
name.append("Cabo Freio")
name.append("Cabo Freio Mão")
name.append("Cabo Freio Mão 1 Grande 1 Pequeno")
name.append("Cabo Puxador Capo")
name.append("Cabo Tampa Traseira")
name.append("Cabo Vela Ignição")
name.append("Cabo Veloc.")
name.append("Cabo Velocímetro")
name.append("Caixa Alavanca")
name.append("Caixa Direção")
name.append("Caixa Direção Com Articulação")
name.append("Caixa Direção Completa")
name.append("Caixa Direção Mecânica")
name.append("Caixa Externa")
name.append("Caixa Filtro Ar")
name.append("Caixa Radiador Inferior")
name.append("Caixa Interna")
name.append("Caixa Radiador")
name.append("Caixa Radiador Lado Direito")
name.append("Caixa Rótula Câmbio")
name.append("Caixa Radiador Superior")
name.append("Caixa Válvula Termostática")
name.append("Calço 026")
name.append("Calço 032")
name.append("Calço 038")
name.append("Calço Amortecedor")
name.append("Calço Feixe Mola")
name.append("Calha")
name.append("Calota")
name.append("Calotinha Cubo Traseiro")
name.append("Câmara Ar")
name.append("Câmara Válvula Termostática")
name.append("Cambagem Dianteira")
name.append("Câmbio")
name.append("Câmbio Completo")
name.append("Câmbio Garfos")
name.append("Câmbio UT-158")
name.append("Cangalha")
name.append("Cano 10723")
name.append("Cano Água")
name.append("Cano Água 3 Saídas")
name.append("Cano Água Fero 3 Saída")
name.append("Cano Água Motor")
name.append("Cano Cilindro Mestre")
name.append("Capa Cabo")
name.append("Capa Correia Dentada")
name.append("Capa Correia Dentada Interna")
name.append("Capa Tucho")
name.append("Capsula Válvula Admissão")
name.append("Car80")
name.append("Carburador")
name.append("Carburador Completo")
name.append("Carcaça Bomba Água")
name.append("Carcaça Válvula Termostática")
name.append("Carcaça Motor")
name.append("Carcaça Reguladora Pressão")
name.append("Carga Bateria")
name.append("Cárter Motor")
name.append("Cárter Óleo")
name.append("Catalisador")
name.append("Catraca Embreagem")
name.append("Cavalete")
name.append("Cavalete Água")
name.append("Cavalete Água 3 Saídas")
name.append("Cavalete Com Sensor Injeção")
name.append("Cavalete Sensor Temperatura")
name.append("Cavalete Válvula Termostática Com Ar Quente")
name.append("Cavalete Válvula Termostática Sem Ar Quente")
name.append("Cebolão Radiador")
name.append("Cebolinha Óleo")
name.append("Cebolinha Óleo 3 Fios")
name.append("Cebolinha Óleo Inter")
name.append("Cebolinha Óleo Plugue Eletrônico")
name.append("Cebolinha Re")
name.append("Centralina Ignição")
name.append("Chapa")
name.append("Chapa Alavanca")
name.append("Chapa Com fuso Tensor")
name.append("Chapa Guia")
name.append("Chapa Guia Marcha Re")
name.append("Chapa Motor")
name.append("Chapa Proteção Volante")
name.append("Chapa Superior Motor")
name.append("Chapeuzinho Balancinho")
name.append("Chave Comutadora")
name.append("Chave Comutadora Completa")
name.append("Chave Emuladora Gás")
name.append("Chave Roda")
name.append("Chave Seletora")
name.append("Chave Seta")
name.append("Chave Seta Completa")
name.append("Chaveta")
name.append("Chicote")
name.append("Chicote Alarme")
name.append("Chicote Atuador")
name.append("Chicote Bico")
name.append("Chicote Bobina")
name.append("Chicote Bomba")
name.append("Chicote Cebolinha")
name.append("Chicote Distribuidor")
name.append("Chicote Ignição")
name.append("Chicote Sensor")
name.append("Chicote Tampa")
name.append("Chip Chave")
name.append("Cilindro Câmbio")
name.append("Cilindro Chave")
name.append("Cilindro Comando")
name.append("Cilindro Embreagem")
name.append("Cilindro Embreagem Pedal")
name.append("Cilindro Freio Dianteiro Esquerdo")
name.append("Cilindro Freio Dianteiro Direito")
name.append("Cilindro Freio Traseiro Esquerdo")
name.append("Cilindro Freio Traseiro Direito")
name.append("Cilindro Mestre")
name.append("Cilindro Mestre Com 4 Saídas")
name.append("Cinta Plástica")
name.append("Coifa")
name.append("Coifa Amortecedor")
name.append("Coifa Braco")
name.append("Coifa Caixa Direção")
name.append("Coifa Câmbio")
name.append("Coifa Câmbio Com Rolamento")
name.append("Coifa Direção")
name.append("Coifa Homocinética Lado Direito")
name.append("Coifa Homocinética Lado Esquerdo")
name.append("Coifa Homocinética Roda")
name.append("Coifa Interna Com Rolamento")
name.append("Coifa Trambulador")
name.append("Cola")
name.append("Cola 3 M")
name.append("Cola Araldite")
name.append("Cola Branca")
name.append("Cola Juntas")
name.append("Cola Multi Vedante")
name.append("Cola Preta")
name.append("Cola Silicone")
name.append("Cola Silicone Branca")
name.append("Cola Silicone Loktaite")
name.append("Cola Silicone Preta")
name.append("Cola Veda Escape")
name.append("Coletor Admissão")
name.append("Coletor Admissão Completo")
name.append("Coletor Escapamento")
name.append("Coluna Barra Direção")
name.append("Coluna Direção")
name.append("Comando Admissão")
name.append("Comando Balancinho")
name.append("Comando Escape")
name.append("Comando Válvula")
name.append("Combustível")
name.append("Comutador")
name.append("Comutador Completo")
name.append("Comutador Partida")
name.append("Condensador")
name.append("Conector Bico Solto")
name.append("Conector Cabo")
name.append("Conector Distribuidor")
name.append("Conector Filtro")
name.append("Conector Flauta")
name.append("Conector Lateral Alternador")
name.append("Conector Mangueira Gás")
name.append("Conector Quatro Vias")
name.append("Conector Reservatório Gasolina")
name.append("Conexão Cabeçote")
name.append("Conexão Coletor")
name.append("Conexão Cotovelo")
name.append("Conexão Entrada Água")
name.append("Conexão Mangueira")
name.append("Conexão Termostática")
name.append("Conjunto 5ª")
name.append("Conjunto Alavanca Câmbio")
name.append("Conjunto Bomba Usado")
name.append("Conjunto Câmbio")
name.append("Conjunto Ré")
name.append("Copo Bomba")
name.append("Copo Tucho")
name.append("Coroa")
name.append("Coroa Pinhão")
name.append("Corpo Borboleta")
name.append("Corpo TBI")
name.append("Corpo TBI Eletrônico")
name.append("Correia")
name.append("Correia Alternador Básica")
name.append("Correia Alternador Direção Hidráulica")
name.append("Correia Alternador Ar Condicionado")
name.append("Correia Alternador Frisada")
name.append("Correia Ar Condicionado")
name.append("Correia Ar Condicionado Direção Hidráulica")
name.append("Correia Bomba D'água")
name.append("Correia Comando Válvula")
name.append("Correia Dentada")
name.append("Correia Direção Hidráulica")
name.append("Correia Diversos")
name.append("Corrente Comando")
name.append("Cotovelo Ar Quente")
name.append("Cotovelo Carcaça")
name.append("Cotovelo Tampão Cht")
name.append("Cotovelo Válvula Termostática")
name.append("Coxim Amortecedor Traseiro Lado Esquerdo")
name.append("Coxim Amortecedor Traseiro Lado Direito")
name.append("Coxim Amortecedor Dianteiro Lado Esquerdo")
name.append("Coxim Amortecedor Dianteiro Lado Direito")
name.append("Coxim Biela")
name.append("Coxim Braço")
name.append("Coxim Câmbio Inferior")
name.append("Coxim Câmbio Superior")
name.append("Coxim Canoinha")
name.append("Coxim Eixo Traseira")
name.append("Coxim Motor Dianteiro Lado Direito")
name.append("Coxim Motor Dianteiro Lado Esquerdo")
name.append("Coxim Motor Traseiro Direito")
name.append("Coxim Motor Traseiro Esquerdo")
name.append("Coxim Radiador")
name.append("Coxim Tensor Motor")
name.append("Cruzeta Barra Direção")
name.append("Cruzeta Cardam")
name.append("Cubo Roda Dianteiro Lado Direito")
name.append("Cubo Roda Dianteiro Lado Esquerdo")
name.append("Cubo Roda Traseira Lado Direito")
name.append("Cubo Roda Traseira Lado Esquerdo")
name.append("Descarbonização")
name.append("Deslizante Câmbio")
name.append("Deslizante Lado Direito")
name.append("Diafragma Pressão")
name.append("Diagnostico Com Scanner")
name.append("Direção Hidráulica")
name.append("Disco Embreagem")
name.append("Disco Freio")
name.append("Disco Freio Sólido Dianteiro")
name.append("Disco Freio Sólido Traseiro")
name.append("Disco Freio Ventilado Dianteiro")
name.append("Disco Freio Ventilado Traseiro")
name.append("Distribuidor")
name.append("Eixo Câmbio Lado Direito")
name.append("Eixo Comando")
name.append("Eixo Homocinética")
name.append("Eixo Homocinética Direito")
name.append("Eixo Homocinética Esquerdo")
name.append("Eixo Pedal Embreagem")
name.append("Eixo Piloto")
name.append("Eixo Traseiro")
name.append("Eletrobomba")
name.append("Embreagem")
name.append("Embreagem Distribuidor")
name.append("Embuchamento Dianteiro")
name.append("Embuchamento Traseiro")
name.append("Emulador Bicos")
name.append("Encosto Balancinho")
name.append("Engate Cabo Trambulador")
name.append("Engrenagem")
name.append("Engrenagem 1ª")
name.append("Engrenagem 2ª")
name.append("Engrenagem 3ª")
name.append("Engrenagem 4ª")
name.append("Engrenagem 5ª")
name.append("Engrenagem Correia Dentada")
name.append("Engrenagem Distribuidor")
name.append("Engrenagem Ré")
name.append("Escapamento")
name.append("Escapamento Com 2 Ponteira")
name.append("Escora")
name.append("Escora Balancim")
name.append("Escora Válvula")
name.append("Escova Alternador")
name.append("Escova Ventoinha")
name.append("Espaçador")
name.append("Esticador Correia Alternador")
name.append("Esticador Correia Alternador Frisado")
name.append("Esticador Correia Ar")
name.append("Esticador Correia Dentada")
name.append("Esticador Corrente")
name.append("Esticador Direção Com Ar")
name.append("Esticador Liso")
name.append("Esticadores Correia Direção")
name.append("Extintor")
name.append("Farol Lado Direito")
name.append("Farol Lado Esquerdo")
name.append("Fechadura Porta")
name.append("Fechadura Tampa Traseiro")
name.append("Fecho Mola")
name.append("Feixe Mola")
name.append("Filtro Anti Chama Motor")
name.append("Filtro Ar")
name.append("Filtro Ar Condicionado")
name.append("Filtro Combustível")
name.append("Filtro Combustível Com Regulador")
name.append("Filtro Óleo")
name.append("Flange Bomba Combustível")
name.append("Flauta")
name.append("Flauta Completa")
name.append("Flexível")
name.append("Flexível Cabo Embreagem")
name.append("Flexível Freio Dianteiro Lado Direito")
name.append("Flexível Freio Dianteiro Lado Esquerdo")
name.append("Flexível Freio Traseiro Lado Direito")
name.append("Flexível Freio Traseira Lado Esquerdo")
name.append("Flexível Pinça Dianteiro")
name.append("Fluido Direção Hidráulica")
name.append("Fluido Embreagem")
name.append("Fluido Freio Dot3")
name.append("Fluido Freio Dot4")
name.append("Fluxo Ar")
name.append("Fluxo Ar Usado")
name.append("Folha Porta")
name.append("Freio Mão")
name.append("fuso Bandeja")
name.append("fuso Bolacha")
name.append("fuso Bomba Água")
name.append("fuso Cabeçote")
name.append("fuso Com Porca Coletor")
name.append("fuso Comando")
name.append("fuso Coxim")
name.append("fuso Coxim Motor")
name.append("fuso Engrenagem")
name.append("fuso Engrenagem Vira")
name.append("fuso Flauta")
name.append("fuso Homocinética")
name.append("fuso Lataria")
name.append("fuso Pinça")
name.append("fuso Pivô")
name.append("fuso Polia Vira")
name.append("fuso Que Prende O Pivô Na Bandeja")
name.append("fuso Regulador Válvula")
name.append("fuso Roda")
name.append("fuso Roda D E")
name.append("fuso Roda Dianteiro")
name.append("fuso Roda Traseira")
name.append("fuso Rodas")
name.append("fuso Semi Eixo")
name.append("fuso Solto")
name.append("fuso Suporte Motor")
name.append("fuso Suspensão")
name.append("fuso Tensor Dentada")
name.append("fuso Trava Pivô Bandeja")
name.append("fuso Virabrequim")
name.append("fuso Volante")
name.append("Garfo 1ª")
name.append("Garfo 2ª")
name.append("Garfo 3ª")
name.append("Garfo 4ª")
name.append("Garfo 5ª")
name.append("Garfo Embreagem")
name.append("Garfo Ré")
name.append("Garfo Seletor Câmbio")
name.append("Garfo Trambulador")
name.append("Grampo Bandeja")
name.append("Graxa Azul")
name.append("Graxa Marfak")
name.append("Guarda Po Amortecedor")
name.append("Guarda Pó Caixa Direção")
name.append("Guarnição Assoalho")
name.append("Guarnição Bomba Combustível")
name.append("Guarnição Câmbio")
name.append("Guarnição Flange Bomba Combustível")
name.append("Guarnição Tampa Bomba Combustível")
name.append("Guia Alavanca")
name.append("Guia Alternador")
name.append("Guia Correia Alternador")
name.append("Guia Correia Dentada")
name.append("Guia Corrente")
name.append("Guia Garfo Embreagem")
name.append("Guia Tensor")
name.append("Guia Vareta Óleo")
name.append("Haste Articulação Comum")
name.append("Haste Trambulador")
name.append("Hidrovácuo Freio")
name.append("Homocinética Interna Lado Esquerdo")
name.append("Homocinética Interna Lado Direito")
name.append("Homocinética Externa Lado Esquerdo")
name.append("Homocinética Externa Lado Direito")
name.append("Ilho Tampa")
name.append("Injetor Carburador")
name.append("Interruptor Luz Freio")
name.append("Interruptor Luz Ré")
name.append("Interruptor Óleo")
name.append("Interruptor Pedal Embreagem")
name.append("Interruptor Pedal Freio")
name.append("Interruptor Pressão Óleo")
name.append("Interruptor Radiador")
name.append("Interruptor Ré")
name.append("Interruptor Temperatura")
name.append("Junta Boia Combustível")
name.append("Junta Bomba Água")
name.append("Junta Bomba Combustível")
name.append("Junta Bomba Óleo")
name.append("Junta Cabeçote")
name.append("Junta Câmara")
name.append("Junta Câmbio")
name.append("Junta Cano Água")
name.append("Junta Carburador")
name.append("Junta Cárter")
name.append("Junta Cárter Câmbio")
name.append("Junta Cárter Com Defletor")
name.append("Junta Cavalete Bomba Água")
name.append("Junta Coletor Admissão")
name.append("Junta Coletor Escape")
name.append("Junta Defletora")
name.append("Junta Diferencial")
name.append("Junta Distribuidor")
name.append("Junta Diversas")
name.append("Junta Escapamento")
name.append("Junta Frange Comando")
name.append("Junta Frontal")
name.append("Junta Gaiola")
name.append("Junta Homocinética")
name.append("Junta Liquida")
name.append("Junta Mini Cárter")
name.append("Junta Motor")
name.append("Junta Pescador")
name.append("Junta Respiro Motor")
name.append("Junta Retifica")
name.append("Junta Semi Cárter")
name.append("Junta Silicone")
name.append("Junta Sistema Refrigeração")
name.append("Junta Suporte Filtro Óleo")
name.append("Junta Tampa Comando")
name.append("Junta Tampa Controle")
name.append("Junta Tampa Corrente")
name.append("Junta Tampa Diferencial")
name.append("Junta Tampa Distribuição")
name.append("Junta Tampa Gaiola")
name.append("Junta Tampa Óleo")
name.append("Junta Tampa Seletora")
name.append("Junta Tampa Trambulador")
name.append("Junta Tampa Válvula")
name.append("Junta Tanque")
name.append("Junta TBI")
name.append("Junta Trambulador Câmbio")
name.append("Junta Tubo Água")
name.append("Junta Válvula Termostática")
name.append("Junta Vareta Óleo")
name.append("K80")
name.append("Kit Acoplamento")
name.append("Kit Adaptação Bomba")
name.append("Kit Alavanca Câmbio")
name.append("Kit Alinhamento")
name.append("Kit Amortecedor Dianteiro")
name.append("Kit Amortecedor Traseiro")
name.append("Kit Anel Bico")
name.append("Kit Anel Tubo Água")
name.append("Kit Barra Estabilizadora")
name.append("Kit Batente Amortecedor Dianteiro")
name.append("Kit Batente Amortecedor Traseiro")
name.append("Kit Batente Dianteiro")
name.append("Kit Batente Traseiro")
name.append("Kit Bico Injetor")
name.append("Kit Borracha Bico")
name.append("Kit Braço Oscilante")
name.append("Kit Braço Tensor")
name.append("Kit Bucha Caixa Direção")
name.append("Kit Bucha Estabilizador")
name.append("Kit Câmbio")
name.append("Kit Camisa")
name.append("Kit Carburador")
name.append("Kit Coifa")
name.append("Kit Comando")
name.append("Kit Correia Dentada")
name.append("Kit Corrente Comando")
name.append("Kit Corrente Distribuição")
name.append("Kit Corrente Tensor")
name.append("Kit Distribuição")
name.append("Kit Embreagem")
name.append("Kit Estabilizador")
name.append("Kit Feixe Mola Traseira")
name.append("Kit fuso Assoalho")
name.append("Kit fuso Lataria")
name.append("Kit Injeção")
name.append("Kit Junta Carburador")
name.append("Kit Junta Coletor")
name.append("Kit Junta Injeção")
name.append("Kit Junta Motor")
name.append("Kit Junta Retificação Cabeçote")
name.append("Kit Junta Tampa Válvula")
name.append("Kit Junta TBI")
name.append("Kit Lona")
name.append("Kit Medidor Combustível")
name.append("Kit Modulo")
name.append("Kit Mola Freio Dianteiro")
name.append("Kit Mola Freio Traseiro")
name.append("Kit Mola Sapata")
name.append("Kit Mola Traseiro")
name.append("Kit Motor")
name.append("Kit O-ring Bico")
name.append("Kit Pedal")
name.append("Kit Peneira Bico")
name.append("Kit Pino Pastilha")
name.append("Kit Proteção Correia Dentada")
name.append("Kit Regulagem")
name.append("Kit Reparo Atuador Embreagem")
name.append("Kit Reparo Patim Traseiro")
name.append("Kit Reparo Pinça Freio")
name.append("Kit Reparo TBI")
name.append("Kit Reparo Trambulador")
name.append("Kit Retificação Cabeçote")
name.append("Kit Rolamento Roda Dianteiro")
name.append("Kit Rolamento Roda Traseiro")
name.append("Kit Suspensão Dianteiro")
name.append("Kit Suspensão Traseiro")
name.append("Kit Tampa Válvula")
name.append("Kit TBI")
name.append("Kit Tensionador Correia Dentada")
name.append("Kit Tensionador Correia Alternador")
name.append("Kit Trambulador Câmbio")
name.append("Kit Trava Patim")
name.append("Kit Vedador Caixa Termostática")
name.append("Lâmpada 1 Polo")
name.append("Lâmpada 2 Polo")
name.append("Lampada Farol")
name.append("Lampada Farol Baixo")
name.append("Lampada Freio")
name.append("Lampada H7")
name.append("Lampada Interna")
name.append("Lampada Ré")
name.append("Lanterna")
name.append("Lavagem")
name.append("Lavagem Completa")
name.append("Lavagem Higienização")
name.append("Lavagem Motor")
name.append("Liame Trambulador")
name.append("Ligação Água")
name.append("Limpa Contato")
name.append("Limpador Brisa")
name.append("Limpeza")
name.append("Limpeza Acelerador Corpo Borboleta")
name.append("Limpeza Agulha Carburador")
name.append("Limpeza Anti Chamas")
name.append("Limpeza Ar Condicionado")
name.append("Limpeza Aranha")
name.append("Limpeza Arrefecimento")
name.append("Limpeza Bico")
name.append("Limpeza Calibração Bicos Injetores")
name.append("Limpeza Carburador")
name.append("Limpeza Cárter")
name.append("Limpeza Cilindro")
name.append("Limpeza Corpo Borboleta")
name.append("Limpeza Corpo TBI")
name.append("Limpeza Freio")
name.append("Limpeza Motor")
name.append("Limpeza Motor Passos")
name.append("Limpeza Radiador")
name.append("Limpeza Redutor")
name.append("Limpeza Reservatório Água")
name.append("Limpeza Respiro")
name.append("Limpeza Sistema Refrigeração")
name.append("Limpeza Tanque Combustível")
name.append("Limpeza TBI")
name.append("Limpeza Vela Ignição")
name.append("Lixa Ferro")
name.append("Lona")
name.append("Lona Com Patim")
name.append("Lona Freio")
name.append("Lona Freio Traseira")
name.append("Luva 1ª")
name.append("Luva 2ª")
name.append("Luva 3ª ")
name.append("Luva 4 ª")
name.append("Luva 5ª")
name.append("Luva Ré")
name.append("Macaco")
name.append("Maçaneta")
name.append("Maçaneta Banco")
name.append("Mancal 025")
name.append("Mancal Balanceiro")
name.append("Mancalzinho")
name.append("Manga Eixo Lado Esquerdo")
name.append("Manga Eixo Lado Direito")
name.append("Mangueira")
name.append("Mangueira 4 mm")
name.append("Mangueira 5 mm")
name.append("Mangueira 6 mm")
name.append("Mangueira 7 mm")
name.append("Mangueira 8 mm")
name.append("Mangueira Água")
name.append("Mangueira Água Em T")
name.append("Mangueira Água Inferior")
name.append("Mangueira Água K1")
name.append("Mangueira Água Superior")
name.append("Mangueira Água Superior Com Saída No Meio")
name.append("Mangueira Alimenta Hidráulico")
name.append("Mangueira Alimentação")
name.append("Mangueira Anti Chama")
name.append("Mangueira Anti Chama Com Rabicho")
name.append("Mangueira Ar Hidrovácuo")
name.append("Mangueira Ar Quente")
name.append("Mangueira Ar Quente Coletor")
name.append("Mangueira Ar Quente Frente")
name.append("Mangueira Avanço")
name.append("Mangueira Bocal Tanque")
name.append("Mangueira Bomba Água")
name.append("Mangueira Bomba Combustível")
name.append("Mangueira Cano Água")
name.append("Mangueira Cavalete")
name.append("Mangueira Coletor")
name.append("Mangueira Coletor Admissão")
name.append("Mangueira Com Rabicho")
name.append("Mangueira Com Válvula")
name.append("Mangueira Combustível")
name.append("Mangueira Corrugada")
name.append("Mangueira Cotovelo")
name.append("Mangueira Cotovelo Respiro Motor")
name.append("Mangueira Direção Hidráulica")
name.append("Mangueira Diversas")
name.append("Mangueira Embreagem")
name.append("Mangueira Espaguete")
name.append("Mangueira Filtro Ar")
name.append("Mangueira Flauta")
name.append("Mangueira Fluxo Ar")
name.append("Mangueira Hidráulico")
name.append("Mangueira Hidrovácuo")
name.append("Mangueira Inferior Radiador")
name.append("Mangueira Injeção")
name.append("Mangueira Injeção Bomba")
name.append("Mangueira Injeção Eletrônica")
name.append("Mangueira Linha Combustível")
name.append("Mangueira Radiador")
name.append("Mangueira Reservatório")
name.append("Mangueira Respiro")
name.append("Mangueira Respiro Combustível")
name.append("Mangueira Respiro Cotovelo")
name.append("Mangueira Respiro Motor")
name.append("Mangueira Respiro S")
name.append("Mangueira Respiro Tampa Válvula")
name.append("Mangueira Retorno Óleo")
name.append("Mangueira TBI")
name.append("Mangueira Válvula Termostática")
name.append("Mão Obra")
name.append("Medidor Combustível")
name.append("Medidor Fluxo")
name.append("Miolo Câmbio")
name.append("Miolo Catalisador")
name.append("Miolo Chave")
name.append("Módulo")
name.append("Módulo Ignição")
name.append("Módulo Injeção")
name.append("Módulo Rei")
name.append("Módulo Ventoinha")
name.append("Mola Acelerador")
name.append("Mola Alavanca")
name.append("Mola Carburador")
name.append("Mola Diversas")
name.append("Mola Embreagem")
name.append("Mola Inferior")
name.append("Mola Pastilha Freio")
name.append("Mola Sapata")
name.append("Mola Suspensão Dianteira")
name.append("Mola Suspensão Traseira")
name.append("Morceguinho")
name.append("Motor")
name.append("Motor Arranque")
name.append("Motor Injeção")
name.append("Motor Limpador Para-brisa")
name.append("Motor Partida Frio")
name.append("Motor Passo")
name.append("Motor Ventilador")
name.append("Motor Ventoinha")
name.append("O-ring")
name.append("O-ring Bico")
name.append("O-ring Bobina")
name.append("O-ring Das Tulipas")
name.append("O-ring Distribuidor")
name.append("O-ring Lateral")
name.append("O-ring Tubo Água")
name.append("O-ring Vedação")
name.append("O-ring Vedação Bobina")
name.append("O-ring Vedação Tampa Bobina")
name.append("Óleo Câmbio")
name.append("Óleo Diferencial")
name.append("Óleo Direção Hidráulica")
name.append("Óleo Freio Dot 3")
name.append("Óleo Freio Dot 4")
name.append("Óleo Hidráulico")
name.append("Óleo Motor 15w40")
name.append("Óleo Motor 20w50")
name.append("Óleo Motor 5w30")
name.append("Óleo Motor 5w30sl")
name.append("Painel Quadro Radiador")
name.append("Palheta")
name.append("Pastilha Freio Sólido Dianteiro")
name.append("Pastilha Freio Sólido Traseiro")
name.append("Pastilha Freio Ventilado Dianteiro")
name.append("Pastilha Freio Ventilado Traseiro")
name.append("Patim Freio")
name.append("Patim Lona")
name.append("Patim Usado")
name.append("Pedal Acelerador")
name.append("Pedal Eletrônico")
name.append("Peneirinha Bico")
name.append("Peneirinha Cárter")
name.append("Pescador Bomba Óleo")
name.append("Pinça Freio")
name.append("Pinhão Cabo Velocímetro")
name.append("Pinhão Coroa")
name.append("Pinhão Distribuidor")
name.append("Pinhão Velocímetro")
name.append("Pino")
name.append("Pino Central")
name.append("Pino Elástico")
name.append("Pino Freio Mão")
name.append("Pino Haste")
name.append("Pino Pedal")
name.append("Pino Pedal Embreagem")
name.append("Pino Pistão")
name.append("Pino Planetário")
name.append("Pintura")
name.append("Pistão")
name.append("Pistão 040")
name.append("Pistão 050")
name.append("Pistão Anel")
name.append("Pistão Anel 040")
name.append("Pistão Anel 050")
name.append("Pistão Anel 060")
name.append("Pistão Anel 1 mm")
name.append("Pistão Anel 10 mm")
name.append("Pistão Anel Camisa")
name.append("Pistão Anel Std")
name.append("Pivô")
name.append("Pivô Bandeia Lado Esquerdo")
name.append("Pivô Bandeja Lado Direito")
name.append("Pivô Braco Oscilante")
name.append("Pivô Suspensão Superior Lado Direito")
name.append("Pivô Suspensão Superior Lado Esquerdo")
name.append("Pivô Suspensão Inferior Lado Esquerdo")
name.append("Pivô Suspensão Inferior Lado Direito")
name.append("Pivô Tirante")
name.append("Planetária")
name.append("Platô Embreagem")
name.append("Plugue Eletrônico")
name.append("Plugue Eletrônico Água")
name.append("Plugue Eletrônico Ar")
name.append("Plugue Eletrônico Azul")
name.append("Plugue Eletrônico Cinza")
name.append("Plugue Eletrônico Injeção")
name.append("Plugue Eletrônico Mte 4050")
name.append("Plugue Eletrônico Sensor Temperatura Injeção")
name.append("Pneu")
name.append("Pneu Alinhamento")
name.append("Pneuzinho Barra Direção")
name.append("Pneuzinho Braço Oscilante")
name.append("Pneuzinho Caixa Direção")
name.append("Polia Alternador")
name.append("Polia Ar Condicionado")
name.append("Polia Bomba D'água")
name.append("Polia Comando Admissão")
name.append("Polia Dianteira Vira Frisado")
name.append("Polia Tensor Correia Alternador")
name.append("Polia Virabrequim")
name.append("Polo Bateria")
name.append("Porca")
name.append("Porca Cabeçote")
name.append("Porca Cabo Embreagem")
name.append("Porca Castelo")
name.append("Porca Diversos")
name.append("Porca Homocinética")
name.append("Porca Roda")
name.append("Porca Rosca")
name.append("Porca Volante")
name.append("Porta Escova")
name.append("Potenciômetro")
name.append("Prato Amortecedor")
name.append("Pré-filtro")
name.append("Presilha Cabo Embreagem")
name.append("Presilha Roda Traseira")
name.append("Prisioneiro 08x180")
name.append("Prisioneiro 08x196")
name.append("Prisioneiro 08x231")
name.append("Prisioneiro Escapamento")
name.append("Prisioneiro Motor")
name.append("Prisioneiro Roda")
name.append("Prisioneiro Tensor Correia Dentada")
name.append("Programação Chave")
name.append("Proteção Coifa Homocinética")
name.append("Proteção Correia Dentada")
name.append("Proteção Correia Dentada Externa")
name.append("Proteção Correia Dentada Inferior")
name.append("Proteção Correia Dentada Interna")
name.append("Proteção Radiador")
name.append("Protetor Cárter")
name.append("Puxador Porta")
name.append("Radiador Água")
name.append("Radiador Ar Condicionado")
name.append("Radiador Óleo")
name.append("RCI-117-UT-360")
name.append("RCI-122-UT-332")
name.append("RCI-18-UT-323")
name.append("RCI-191-UT-325")
name.append("RCI-38 UT-15")
name.append("Rebites Grandes")
name.append("Rebites Lona")
name.append("Refil Bomba Combustível")
name.append("Reforço Dianteiro Esquerdo")
name.append("Regulador Alternador")
name.append("Regulador Pressão Combustível")
name.append("Regulador Válvula")
name.append("Rele Bomba Combustível")
name.append("Rele Injeção")
name.append("Remendo Pneu")
name.append("Reparo Alavanca Câmbio")
name.append("Reparo Alavanca Freio Mão")
name.append("Reparo Alternador")
name.append("Reparo Bandeja")
name.append("Reparo Bico")
name.append("Reparo Coletor")
name.append("Reparo Bomba Direção Hidráulico")
name.append("Reparo Cabo")
name.append("Reparo Caixa Direção")
name.append("Reparo Câmbio")
name.append("Reparo Carburador")
name.append("Reparo Chicote")
name.append("Reparo Completo Gnv")
name.append("Reparo Compressor Ar")
name.append("Reparo Feixe Mola")
name.append("Reparo Injeção")
name.append("Reparo Modulo")
name.append("Reparo Pinça")
name.append("Reparo Pino Guia")
name.append("Reparo Radiador")
name.append("Reparo Tensor")
name.append("Reparo Trambulador Câmbio")
name.append("Reparo Turbina")
name.append("Reparo Válvula Injeção")
name.append("Reprogramação")
name.append("Reprogramação Das Chaves")
name.append("Reprogramação Eletrônica")
name.append("Reservatório Água")
name.append("Reservatório Água Com Tampa")
name.append("Reservatório Direção Hidráulica")
name.append("Reservatório Gasolina")
name.append("Reservatório Óleo Freio")
name.append("Resistência Ar Condicionado")
name.append("Resistência Desembaçador")
name.append("Resistência Ventilação Forçada")
name.append("Respiro Câmbio")
name.append("Respiro Carter")
name.append("Respiro Motor")
name.append("Retentor Auxiliar")
name.append("Retentor Boma Água")
name.append("Retentor Bomba Óleo")
name.append("Retentor Caixa Direção")
name.append("Retentor Câmbio")
name.append("Retentor Cardan")
name.append("Retentor Cárter")
name.append("Retentor Comando Admissão")
name.append("Retentor Comando Escape")
name.append("Retentor Comando Auxiliar")
name.append("Retentor Comando Bomba Óleo")
name.append("Retentor Comando Distribuidor")
name.append("Retentor Comando Válvula Admissão")
name.append("Retentor Comando Válvula Escape")
name.append("Retentor Correia Dentada")
name.append("Retentor Cubo Roda")
name.append("Retentor Dianteiro Motor")
name.append("Retentor Dianteiro Polia")
name.append("Retentor Dianteiro Trambulador")
name.append("Retentor Dianteiro Virabrequim")
name.append("Retentor Diferencial")
name.append("Retentor Distribuidor")
name.append("Retentor Eixo Câmbio")
name.append("Retentor Eixo Comando")
name.append("Retentor Eixo Distribuidor")
name.append("Retentor Eixo Piloti")
name.append("Retentor Eixo Traseiro")
name.append("Retentor Haste Seletora")
name.append("Retentor Haste Trambulador")
name.append("Retentor Lateral Câmbio")
name.append("Retentor Mancal Traseiro")
name.append("Retentor Motor")
name.append("Retentor Piloto")
name.append("Retentor Polia Motor")
name.append("Retentor Ponta Comando")
name.append("Retentor Roda Dianteira")
name.append("Retentor Roda Externo")
name.append("Retentor Roda Interno")
name.append("Retentor Roda Traseira")
name.append("Retentor Semi Eixo")
name.append("Retentor Tambor")
name.append("Retentor Tampa Válvula")
name.append("Retentor Trambulador Câmbio")
name.append("Retentor Traseiro Motor")
name.append("Retentor Traseiro Virabrequim")
name.append("Retentor Traseiro Volante")
name.append("Retentor Tulipa")
name.append("Retentor Virabrequim Dianteiro")
name.append("Retentor Virabrequim Traseiro")
name.append("Retentor Volante")
name.append("Retentor Volante Motor")
name.append("Retentor Volante Traseiro")
name.append("Retifica")
name.append("Retífica")
name.append("Retifica Biela")
name.append("Retifica Bloco")
name.append("Retifica Cabeçote")
name.append("Retifica Cabeçote Completo")
name.append("Retifica Disco")
name.append("Retifica Embuchar")
name.append("Retifica Motor")
name.append("Retifica Plaina Solda")
name.append("Retifica Rosca")
name.append("Retifica Tambor")
name.append("Retifica Teste Trinca Plaina")
name.append("Retrovisor")
name.append("Revestimento Radiador Completo")
name.append("Roda Ferro")
name.append("Rolamento Alternador")
name.append("Rolamento Auxiliar Correia Alternador")
name.append("Rolamento Auxiliar Correia Dentada")
name.append("Rolamento Câmbio")
name.append("Rolamento Cardan")
name.append("Rolamento Coifa")
name.append("Rolamento Coluna Direção")
name.append("Rolamento Correia Alternador")
name.append("Rolamento Correia Ar Condicionado")
name.append("Rolamento Correia Dentada")
name.append("Rolamento Cubo Roda")
name.append("Rolamento Duplo Câmbio")
name.append("Rolamento Eixo Piloto")
name.append("Rolamento Embreagem")
name.append("Rolamento Esticador Correia Alternador")
name.append("Rolamento Externo Eixo Traseiro")
name.append("Rolamento Guia Correia Alternador")
name.append("Rolamento Guia Correia Ar Condicionado")
name.append("Rolamento Guia Correia Dentada")
name.append("Rolamento Guia Correia Direção Hidráulica")
name.append("Rolamento Guia Direção")
name.append("Rolamento Guia Piloto")
name.append("Rolamento Interno Eixo Traseiro")
name.append("Rolamento Lateral Coroa")
name.append("Rolamento Poli V")
name.append("Rolamento Roda Dianteiro")
name.append("Rolamento Roda Traseiro")
name.append("Rolamento Semi Eixo")
name.append("Rolamento Suspensão")
name.append("Rolamento Tensor Correia Alternador")
name.append("Rolamento Tensor Correia Ar Condicionado")
name.append("Rolamento Tensor Correia Dentada")
name.append("Rolamento Tensor Poli V")
name.append("Rolamento Ventoinha")
name.append("Rosca Cabeçote")
name.append("Rosca Cárter")
name.append("Rosca Tampa Bomba")
name.append("Rosca Tanque")
name.append("Rosca Tensor")
name.append("Rotor Alternador")
name.append("Rotor Distribuidor")
name.append("Rotula Alavanca Câmbio")
name.append("Sapata Freio Traseira")
name.append("Selo Bloco Motor")
name.append("Selo Cabeçote")
name.append("Selo Câmbio")
name.append("Selo Carcaça")
name.append("Selo Coletor Admissão")
name.append("Selo Comando Válvula")
name.append("Semieixo Homocinética")
name.append("Semieixo Câmbio")
name.append("Sensor Abs")
name.append("Sensor Borboleta")
name.append("Sensor Correia Dentada")
name.append("Sensor Detonação")
name.append("Sensor Fase")
name.append("Sensor Fluxo Ar")
name.append("Sensor Hall")
name.append("Sensor Injeção")
name.append("Sensor Macha Lenta")
name.append("Sensor MAP")
name.append("Sensor Modulo")
name.append("Sensor Óleo")
name.append("Sensor Pedal Freio")
name.append("Sensor Re")
name.append("Sensor Rotação")
name.append("Sensor TBI")
name.append("Sensor Temperatura Água")
name.append("Sensor Temperatura Ar")
name.append("Sensor Temperatura Injeção")
name.append("Sensor Velocidade")
name.append("Servo Freio")
name.append("Silencioso")
name.append("Silicone Alta Temp Wurt 1826")
name.append("Silicone Branco")
name.append("Silicone Cárter")
name.append("Silicone Preto")
name.append("Sonda Lambda")
name.append("Spray Preto")
name.append("Suporte Alavanca")
name.append("Suporte Alternador")
name.append("Suporte Cabeçote")
name.append("Suporte Caixa")
name.append("Suporte Câmbio")
name.append("Suporte Correia Dentada")
name.append("Suporte Coxim")
name.append("Suporte Filtro Ar")
name.append("Suporte Flexível")
name.append("Suporte Frontal")
name.append("Suporte Motor")
name.append("Suporte Plugue")
name.append("Suporte Tampa Óleo")
name.append("Suporte Tensor Correia")
name.append("Suporte Trambulador")
name.append("Suporte Ventoinha")
name.append("Suspensão")
name.append("Tambor Freio Dianteiro")
name.append("Tambor Freio Traseiro")
name.append("Tampa Bomba")
name.append("Tampa Bomba Com Regulador Pressão")
name.append("Tampa Bomba Combustível")
name.append("Tampa Cabeçote")
name.append("Tampa Carcaça Bomba Água")
name.append("Tampa Carcaça Bomba Combustível")
name.append("Tampa Carcaça Válvula Termostática")
name.append("Tampa Cárter")
name.append("Tampa Comando Válvula")
name.append("Tampa Combustível")
name.append("Tampa Motor")
name.append("Tampa Óleo")
name.append("Tampa Reservatório Água")
name.append("Tampa Reservatório Água Para-brisa")
name.append("Tampa Reservatório Direção Hidráulica")
name.append("Tampa Reservatório Radiador")
name.append("Tampa Seletora Câmbio")
name.append("Tampa Seletora Câmbio Com Retentor")
name.append("Tampa Tanque")
name.append("Tampa Válvula Termostática")
name.append("Tampão")
name.append("Tampão Ar Quente")
name.append("Tampão Bloco")
name.append("Tampão Bomba Água")
name.append("Tampao Cabeçote")
name.append("Tampão Comando Válvula")
name.append("Tampão Traseiro Câmbio")
name.append("Tampão Traseiro Comando")
name.append("Tampão Tubo Água")
name.append("Tanque Combustível")
name.append("TBI")
name.append("Tensor Correia Alternador")
name.append("Tensor Correia Ar Condicionado")
name.append("Tensor Correia Dentada")
name.append("Tensor Correia Direção Hidráulica")
name.append("Tensor Poli V")
name.append("Tensor Posição Borboleta")
name.append("Tensor Rolo Guia Alternador")
name.append("Terminal Axial Direção")
name.append("Terminal Bateria")
name.append("Terminal Direção Fêmea")
name.append("Terminal Distribuidor")
name.append("Torre Amortecedor")
name.append("Trambulador Alavanca")
name.append("Trambulador Câmbio")
name.append("Trambulador Marcha")
name.append("Trambulador Rotula")
name.append("Trava Cabo Embreagem")
name.append("Trava Coroa")
name.append("Trava Elétrica")
name.append("Trava Homocinética")
name.append("Trava Pastilha Traseira")
name.append("Trava Rolamento")
name.append("Trava Tulipa")
name.append("Travessa")
name.append("Triângulo")
name.append("Tubo Água")
name.append("Tubo Água Alumínio")
name.append("Tubo Água Motor")
name.append("Tubo Água Plástico 2 Saídas")
name.append("Tubo Água Radiador")
name.append("Tubo Combustível")
name.append("Tubo Flexível Embreagem")
name.append("Tubo Freio")
name.append("Tubo Homogeneizador")
name.append("Tubo Injetor")
name.append("Tubo Vareta Óleo")
name.append("Tucho Hidráulico")
name.append("Tucho Motor")
name.append("Tucho Válvula")
name.append("Tucho Vela Ignição")
name.append("Tulipa Câmbio")
name.append("Turbina")
name.append("Unidade Comando")
name.append("UT-102")
name.append("UT-103")
name.append("UT-107")
name.append("UT-110")
name.append("UT-116")
name.append("UT-121")
name.append("UT-126")
name.append("UT-127")
name.append("UT-128")
name.append("UT-138")
name.append("UT-144")
name.append("UT-15")
name.append("UT-154")
name.append("UT-157")
name.append("UT-158")
name.append("UT-159")
name.append("UT-176")
name.append("UT-185")
name.append("UT-186")
name.append("UT-194")
name.append("UT-225")
name.append("UT-226")
name.append("UT-316")
name.append("UT-321")
name.append("UT-323")
name.append("UT-325")
name.append("UT-331")
name.append("UT-332")
name.append("UT-334")
name.append("UT-335")
name.append("UT-336")
name.append("UT-337")
name.append("UT-341")
name.append("UT-343")
name.append("UT-344")
name.append("UT-349")
name.append("UT-352")
name.append("UT-356")
name.append("UT-360")
name.append("UT-367")
name.append("UT-379")
name.append("UT-397")
name.append("UT-398")
name.append("UT-433")
name.append("UT-64")
name.append("UT-72")
name.append("UT-77")
name.append("UT-89")
name.append("UT-94")
name.append("Ut159")
name.append("Ut340")
name.append("Ut379")
name.append("Válvula Admissão")
name.append("Válvula Afogador Carburador")
name.append("Válvula Ar Quente")
name.append("Válvula Boia")
name.append("Válvula Duas Vias")
name.append("Válvula Equalizadora Freio")
name.append("Válvula Escape")
name.append("Válvula Freio")
name.append("Válvula Hidrovácuo")
name.append("Válvula Ignição")
name.append("Válvula Injetora")
name.append("Válvula Partida Fria")
name.append("Válvula Pressão Óleo Cabeçote")
name.append("Válvula Reguladora")
name.append("Válvula Reguladora Pressão")
name.append("Válvula Reservatório Gasolina")
name.append("Válvula Retenção Óleo")
name.append("Válvula Solenoide")
name.append("Válvula Termostática")
name.append("Varão Câmbio")
name.append("Varão Trambulador")
name.append("Vareta Comando Válvula")
name.append("Vareta Óleo")
name.append("Vareta Trambulador")
name.append("Vareta Tucho Válvula")
name.append("Vareta Válvula")
name.append("Veda Escape")
name.append("Vela Ignição")
name.append("Vela Tripolar")
name.append("Ventoinha")
name.append("Virabrequim")
name.append("Virabrequim 050")
name.append("WD 40")


for nm in name:
    cur.execute(insertItem, (str(uuid.uuid4()), nm, "PÇ", createdAt, False, createdAt))










conn.commit()
cur.close()
conn.close()
